# Generated by Django 5.0.6 on 2024-06-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='user_name',
            new_name='username',
        ),
    ]
